# Generated by Django 4.2.8 on 2026-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='promos/')),
                ('button_text', models.CharField(default='BATAFSIL', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
