# Generated by Django 4.2.8 on 2026-01-18 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_14b9c0_idx',
            old_name='products_pr_categor_9edb3d_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('noutbuk', 'Noutbuklar'), ('komplekt', 'Komplektlar'), ('monitor', 'Monitorlar'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
